import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:http/http.dart' as http;
import 'package:provider/provider.dart';

import 'package:arham_corporation/config/app_config.dart';
import 'package:arham_corporation/providers/user_provider.dart';
import 'package:arham_corporation/widgets/custom_app_bar.dart';

class TripDetailMapScreen extends StatefulWidget {
  final int tripId;
  final String? userName;

  const TripDetailMapScreen({
    super.key,
    required this.tripId,
    this.userName,
  });

  @override
  State<TripDetailMapScreen> createState() => _TripDetailMapScreenState();
}

class _TripDetailMapScreenState extends State<TripDetailMapScreen> {
  GoogleMapController? _mapController;
  final Set<Marker> _markers = {};
  final Set<Polyline> _polylines = {};
  static const LatLng _defaultCenter = LatLng(23.0225, 72.5714);
  bool _loading = true;
  String? _error;

  Map<String, dynamic>? _tripData;
  List<LatLng> _routePoints = [];

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _fetchTripDetails();
    });
  }

  Future<void> _fetchTripDetails() async {
    final ub = Provider.of<UserProvider>(context, listen: false);
    final token = ub.token;

    if (token == null || token.isEmpty) {
      setState(() {
        _error = 'Missing auth token';
        _loading = false;
      });
      return;
    }

    try {
      final uri =
          Uri.parse('${AppConfig.baseURL}location/trip/${widget.tripId}');
      final response = await http.get(
        uri,
        headers: {
          'Authorization': 'Bearer $token',
          'x-app-type': 'oms',
        },
      );

      if (response.statusCode == 200) {
        final decoded = json.decode(response.body);
        final data = decoded['data'];

        if (data is Map<String, dynamic>) {
          final points = _extractRoutePoints(data);
          setState(() {
            _tripData = data;
            _routePoints = points;
            _loading = false;
          });

          // Build markers and polylines
          _buildMarkersAndPolylines();
        } else {
          setState(() {
            _error = 'Invalid response format';
            _loading = false;
          });
        }
      } else {
        setState(() {
          _error = 'Failed to fetch trip details: ${response.statusCode}';
          _loading = false;
        });
      }
    } catch (e) {
      setState(() {
        _error = 'Error: $e';
        _loading = false;
      });
    }
  }

  List<LatLng> _extractRoutePoints(Map<String, dynamic> tripData) {
    // Route comes from encoded polyline generated by backend.
    final trip = tripData['trip'] as Map<String, dynamic>?;
    if (trip == null) {
      return [];
    }

    final encoded = (trip['polyline_encoded'] ?? '').toString().trim();
    if (encoded.isEmpty) {
      return [];
    }

    try {
      return _decodePolyline(encoded);
    } catch (_) {
      return [];
    }
  }

  List<LatLng> _decodePolyline(String encoded) {
    final points = <LatLng>[];
    int index = 0;
    int lat = 0;
    int lng = 0;

    while (index < encoded.length) {
      int shift = 0;
      int result = 0;

      int b;
      do {
        b = encoded.codeUnitAt(index++) - 63;
        result |= (b & 0x1f) << shift;
        shift += 5;
      } while (b >= 0x20 && index < encoded.length);

      final dLat = (result & 1) != 0 ? ~(result >> 1) : (result >> 1);
      lat += dLat;

      shift = 0;
      result = 0;
      do {
        b = encoded.codeUnitAt(index++) - 63;
        result |= (b & 0x1f) << shift;
        shift += 5;
      } while (b >= 0x20 && index < encoded.length);

      final dLng = (result & 1) != 0 ? ~(result >> 1) : (result >> 1);
      lng += dLng;

      points.add(LatLng(lat / 1e5, lng / 1e5));
    }

    return points;
  }

  void _buildMarkersAndPolylines() {
    _markers.clear();
    _polylines.clear();

    if (_routePoints.isEmpty) {
      if (mounted) {
        setState(() {});
      }
      return;
    }

    final List<LatLng> polylinePoints = List<LatLng>.from(_routePoints);

    // Add markers for start and end points
    final startPoint = _routePoints.first;
    final endPoint = _routePoints.last;

    _markers.add(
      Marker(
        markerId: const MarkerId('start'),
        position: startPoint,
        infoWindow: const InfoWindow(title: 'Start'),
        icon: BitmapDescriptor.defaultMarkerWithHue(
          BitmapDescriptor.hueGreen,
        ),
      ),
    );

    _markers.add(
      Marker(
        markerId: const MarkerId('end'),
        position: endPoint,
        infoWindow: const InfoWindow(title: 'End'),
        icon: BitmapDescriptor.defaultMarkerWithHue(
          BitmapDescriptor.hueRed,
        ),
      ),
    );

    // Create polyline
    _polylines.add(
      Polyline(
        polylineId: const PolylineId('route'),
        points: polylinePoints,
        color: Colors.blue,
        width: 5,
        geodesic: true,
      ),
    );

    // Animate camera to fit all points
    if (_mapController != null) {
      _animateCameraToBounds(polylinePoints);
    }

    if (mounted) {
      setState(() {});
    }
  }

  void _animateCameraToBounds(List<LatLng> points) {
    if (points.isEmpty) return;

    double minLat = points.first.latitude;
    double maxLat = points.first.latitude;
    double minLng = points.first.longitude;
    double maxLng = points.first.longitude;

    for (final point in points) {
      if (point.latitude < minLat) minLat = point.latitude;
      if (point.latitude > maxLat) maxLat = point.latitude;
      if (point.longitude < minLng) minLng = point.longitude;
      if (point.longitude > maxLng) maxLng = point.longitude;
    }

    final bounds = LatLngBounds(
      southwest: LatLng(minLat, minLng),
      northeast: LatLng(maxLat, maxLng),
    );

    _mapController?.animateCamera(
      CameraUpdate.newLatLngBounds(bounds, 100),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: CustomAppBar(
        title: widget.userName != null
            ? '${widget.userName}\'s Route'
            : 'Trip Route',
      ),
      body: _buildBody(),
    );
  }

  Widget _buildBody() {
    if (_error != null) {
      return Center(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text(
                _error!,
                textAlign: TextAlign.center,
                style: const TextStyle(color: Colors.red),
              ),
              const SizedBox(height: 16),
              ElevatedButton(
                onPressed: () {
                  setState(() {
                    _loading = true;
                    _error = null;
                  });
                  _fetchTripDetails();
                },
                child: const Text('Retry'),
              ),
            ],
          ),
        ),
      );
    }

    final initialTarget =
        _routePoints.isNotEmpty ? _routePoints.first : _defaultCenter;

    return Stack(
      children: [
        Column(
          children: [
            Expanded(
              child: GoogleMap(
                onMapCreated: (controller) {
                  _mapController = controller;
                  if (_routePoints.isNotEmpty) {
                    _animateCameraToBounds(_routePoints);
                  }
                },
                initialCameraPosition: CameraPosition(
                  target: initialTarget,
                  zoom: _routePoints.isNotEmpty ? 15 : 12,
                ),
                markers: _markers,
                polylines: _polylines,
                myLocationEnabled: true,
              ),
            ),
            if (_tripData != null)
              Padding(
                padding: const EdgeInsets.all(16.0),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Total Points: ${_routePoints.length}',
                      style: const TextStyle(fontWeight: FontWeight.bold),
                    ),
                    const SizedBox(height: 8),
                    Text(
                      'Trip ID: ${widget.tripId}',
                      style: const TextStyle(fontSize: 12),
                    ),
                  ],
                ),
              ),
          ],
        ),
        if (_loading)
          const Positioned.fill(
            child: ColoredBox(
              color: Color(0x33000000),
              child: Center(child: CircularProgressIndicator()),
            ),
          ),
        if (!_loading && _routePoints.isEmpty)
          Positioned(
            left: 16,
            right: 16,
            bottom: 24,
            child: Container(
              padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(8),
                boxShadow: const [
                  BoxShadow(
                    color: Colors.black26,
                    blurRadius: 6,
                    offset: Offset(0, 2),
                  ),
                ],
              ),
              child: const Text(
                'No polyline points available for this trip.',
                textAlign: TextAlign.center,
              ),
            ),
          ),
      ],
    );
  }

  @override
  void dispose() {
    _mapController?.dispose();
    super.dispose();
  }
}
