workflows:
  ios-release:
    name: iOS Release Build

    max_build_duration: 120

    environment:
      flutter: stable
      xcode: latest

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.arhamerp.app

    integrations:
      app_store_connect: codemagic

    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration