// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhvc3b4v1ZjFdMS-VPzq4S5jisz_G8zRw',
    appId: '1:529342707700:web:12d4b34cba9ed673feeba1',
    messagingSenderId: '529342707700',
    projectId: 'arham-oms',
    authDomain: 'arham-oms.firebaseapp.com',
    storageBucket: 'arham-oms.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3eSlHgerSqQciLN49htQwLbZ4838bfxE',
    appId: '1:529342707700:android:2e4915f0c6696d98feeba1',
    messagingSenderId: '529342707700',
    projectId: 'arham-oms',
    storageBucket: 'arham-oms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIqsx2hlwwLQbSLnHTCfpmCzN06VeWZQU',
    appId: '1:529342707700:ios:e99c0231e57809e3feeba1',
    messagingSenderId: '529342707700',
    projectId: 'arham-oms',
    storageBucket: 'arham-oms.firebasestorage.app',
    iosBundleId: 'com.example.arhamOms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIqsx2hlwwLQbSLnHTCfpmCzN06VeWZQU',
    appId: '1:529342707700:ios:e99c0231e57809e3feeba1',
    messagingSenderId: '529342707700',
    projectId: 'arham-oms',
    storageBucket: 'arham-oms.firebasestorage.app',
    iosBundleId: 'com.example.arhamOms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhvc3b4v1ZjFdMS-VPzq4S5jisz_G8zRw',
    appId: '1:529342707700:web:db592a79020b898cfeeba1',
    messagingSenderId: '529342707700',
    projectId: 'arham-oms',
    authDomain: 'arham-oms.firebaseapp.com',
    storageBucket: 'arham-oms.firebasestorage.app',
  );
}
